### ISSUE TITLE
Can we make this owned by satrdays and not CardiffR?

### ISSUE THREAD

**Issue by DaveParr** [satRdays/badgeR#1]
Thanks for making this @dokato , it was great taht you took the initiative and starting thsi moving. How would you feel if I transferred the ownership of this over to satRdays core? I feel like by putting it there it would gain some visibility and increase the potential for reuse/refinement.

for now I have simply forked it https://github.com/satRdays/badgeR but this means that issues can't be raised and a few other little niggles that means it's not as good a solution.

**Comment by dokato** [comment]
Sure, good idea!

Although now it will be probably in lesser demand due to lack of on-site events :( But I'm sure that once everything gets back to normal it might be useful for other conferences. Would be cool to organise once some hackathon-like Thursday meet-up around that to extend this a little bit.
